# Generated by Django 3.2.9 on 2021-12-09 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0002_auto_20211130_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='BirthDate',
            field=models.DateField(auto_created=True, default='1999-08-01'),
        ),
        migrations.AddField(
            model_name='profile',
            name='Country',
            field=models.CharField(default='', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='Gender',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=25, null=True),
            preserve_default=False,
        ),
    ]
