# Generated by Django 3.2 on 2021-12-18 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0003_auto_20211209_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoApp.master')),
                ('Profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoApp.profile')),
            ],
            options={
                'db_table': 'connection',
            },
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=25)),
                ('Tags', models.CharField(max_length=100)),
                ('Deadline', models.DateTimeField(auto_now_add=True)),
                ('Description', models.TextField(max_length=255)),
                ('Profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoApp.profile')),
            ],
            options={
                'db_table': 'todo',
            },
        ),
        migrations.CreateModel(
            name='ToDoParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Connnection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoApp.connnection')),
                ('ToDo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoApp.todo')),
            ],
            options={
                'db_table': 'ToDoParticipant',
            },
        ),
    ]
