# Generated by Django 3.2 on 2021-12-18 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0004_connnection_todo_todoparticipant'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Connnection',
            new_name='Connection',
        ),
        migrations.RenameField(
            model_name='todoparticipant',
            old_name='Connnection',
            new_name='Connection',
        ),
    ]
