# Generated by Django 3.2 on 2021-12-18 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0005_auto_20211218_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('JobTitles', models.TextField(max_length=255)),
            ],
            options={
                'db_table': 'Department',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='JobTitle',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='RefID',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='Department',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='todoApp.department'),
        ),
    ]
