# Generated by Django 3.2 on 2021-12-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0006_auto_20211218_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='Status',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
