# Generated by Django 3.2 on 2021-12-30 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0007_connection_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ToDoParticipant',
            new_name='ToDoMember',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='Profile',
            new_name='Master',
        ),
        migrations.RemoveField(
            model_name='todomember',
            name='Connection',
        ),
        migrations.AddField(
            model_name='todomember',
            name='Profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoApp.profile'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='todomember',
            table='ToDoMember',
        ),
    ]
