# Generated by Django 3.2 on 2022-01-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0009_alter_todo_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='Deadline',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
