# Generated by Django 3.2 on 2022-01-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0010_alter_todo_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='IsCompleted',
            field=models.BooleanField(default=False),
        ),
    ]
