# Generated by Django 3.2 on 2022-01-25 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0011_todo_iscompleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Avatar',
            field=models.FileField(default='users/profile/avatar.png', upload_to='users/profile/'),
        ),
    ]
